[package]
name = "restream"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]

[dependencies]
bytes = "0.4.6"
tokio = "0.1.1"
tokio-io = "0.1.1"
futures = "0.1.18"
pretty_env_logger = "0.1"
