[package]
name = "restream"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]
license = "GPL-2.0-or-later"

[dependencies]
bytes = "0.4.6"
mio = "0.6"
tokio = "0.1"
tokio-io = "0.1"
tk-listen = "0.2"
futures = "0.1"
pretty_env_logger = "0.1"
structopt = "0.2"
